### ISSUE TITLE
Readme syntax is not valid?

### ISSUE THREAD

**Issue by SpriteMidr** [ltworf/relational#9]
Please excuse me if I am being stupid here, but in the readme, it says `σ age > 25` is valid syntax (I ommitted the "rank" part as there is no attribute or relation under those aliases that I can find.

The issue is, is that it is not classed as being valid?

![image](https://cloud.githubusercontent.com/assets/14885638/15577074/dd71d1c2-2352-11e6-8dda-a1227b74a6ce.png)

I eventually guessed that I was not specifying the relation to look in for these elements. By guessing from other "valid" syntax examples, I realised you need to enter it like so:

` σ age > 25 ( people ) `

...and then it works on the supplied test files. 

The issue could have also been resolved with slightly more informative error messages. I mean, when it says "invalid relation name", I guessed I needed to specify this, however nothing specified that I needed brackets around this. I know it is part of relational algebra, but it just threw me off quite suddenly.

I cannot fault the software itself at all, it is just, I know that there is a website to visit for the manual, but a slightly more informative readme regarding syntax would be awesome :)

**Comment by ltworf** [comment]
Hi.

You copied and pasted half a line from the README. I don't see why you would expect half of an example to be correct.

However, if you want to replace the example in the readme with other examples, feel free to send me a patch.

Identifying the error and providing a nice error message is quite tricky since the failure happens quite early (tokenizer).

I'm closing this.
